### PR TITLE
patch R docs build failure on CI

### LINKED ISSUE #1605: Nightly r-docs failing: maybe because OPENDP_LIB_DIR is undefined?
**Describe the bug**
Nightly is failing, and has been since last month, though it looks like the failure has changed over time, and is now near the end of the CI chain.

**To Reproduce**
[ci logs](https://github.com/opendp/opendp/actions/runs/9056941387/job/24881540577#step:5:30):
```
using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
expected either a src/binary.tar.xz, src/source.tar.xz (run bash tools/r_stage.sh) or OPENDP_LIB_DIR to be set
make: *** [Makevars:16: rust_build] Error 1
ERROR: compilation failed for package ‘opendp’
* removing ‘/tmp/RtmpaKQVmk/devtools_install_17a51673c2d6/opendp’
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'R' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Backtrace:
 1. devtools::document("R/opendp")
...
```

**More broadly...**

Do we need to move more of Nightly into the normal PR CI so that we don't find ourselves surprised by failures like this?

### PR DESCRIPTION
**Pull request by Shoeboxam**
Closes #1605

Provides an alternative docs build that does not rely on the existence of a library binary. Behaves similarly as OPENDP_HEADLESS for Python.

CI Run:
https://github.com/opendp/opendp/actions/runs/9490435694

### CODE REVIEW

**Comment by mccalluc** [comment]
I'll come back to this, but I was hoping the manual run might have pushed r-docs to nightly, but https://docs.opendp.org/en/nightly/api/r/reference/accuracy_to_discrete_gaussian_scale.html is 404. 

My sense is that this is hacky, and ideally it would work differently, but I'm not sure what that ideal looks like. Should there be an issue for that?

(After looking at other PRs, which I expect to be easier, I'll come back to this and try to understand better how it works.)

File: tools/r_stage.sh [hunk 1]
```diff
@@ -94,6 +94,37 @@ function docs() {
   log "R package docs are ready in R/opendp/docs/index.html"
 }
 
+function dummydocs() {
```
Comment (mccalluc) [inline tools/r_stage.sh:97]:
```suggestion
function dummy_docs() {
```

File: tools/r_stage.sh [hunk 2]
```diff
@@ -108,14 +139,15 @@ if (($# == 0)); then
...
-while getopts ":cbsvnd" OPT; do
+while getopts ":cbsvndu" OPT; do
   case "$OPT" in
     c) clean ;;
     b) binary_tar ;;
     s) source_tar ;;
     v) vendor_tar ;;
     n) notes ;;
     d) docs ;;
+    u) dummydocs ;;
```
Comment (mccalluc) [inline tools/r_stage.sh:150]:
```suggestion
    u) dummy_docs ;;
```

**Review by mccalluc — APPROVED** [review]
- Filed #1675

It's going to take me some time to understand this, and even then, the best solution probably isn't going to be obvious. Approving to get nightly fixed.
