### PR TITLE
fix: interactive postprocessing under sequentiality constraint

### LINKED ISSUE #2421: interactive postprocessing under query sequentiality triggers panic
A common pattern in differentially private algorithms is interactive postprocessing of a queryable. A simple example of this is creating an OpenDP measurement that releases a Polars OnceFrame (a queryable), and then chaining with a postprocessor that collects the onceframe (sending a collect query to the underlying queryable). The resulting chained measurement is non-interactive. This behavior similarly arises in PCA, AIM, and the synthetic data wrapper.

OpenDP enforces query sequentiality via wrapping: if a compositor requires query sequentiality, it creates a recursive wrapper that wraps any child queryable in a new queryable that "asks for permission" to execute. The root compositor can choose to dis-allow child queryables from executing, thus enforcing query sequentiality.

The panic arises when a measurement with interactive postprocessing is submitted to a compositor that enforces query sequentiality. OpenDP queryables can only evaluate one query at a time. 

1. Measurement is submitted to compositor queryable. Compositor queryable is now actively evaluating a query.
2. Compositor queryable invokes the measurement.
3. In the process of evaluating the measurement, a child queryable is spawned and wrapped.
4. In the process of evaluating the measurement, the interactive postprocessor queries the child queryable.
5. The child queryable asks for permission to execute from the compositor queryable.
6. The compositor queryable is still actively evaluating a query, so borrowing a mutable reference to the queryable panics.

Therefore all descendants of a compositor queryable that enforce query sequentiality don't support interactive postprocessing.

(I have a fix PR to be opened shortly)

### PR DESCRIPTION
**Pull request by Shoeboxam**
Closes #2421

This PR also drops the Send and Sync bounds for threading. This was primarily added for compatibility with Polars, but was ultimately not necessary. While threading is nice, the extra pain from the bounds compounds with odometers, and we don't seem to need it.

### CODE REVIEW

**Comment by Shoeboxam** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/opendp/opendp/2450?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#678** <a href="https://app.graphite.dev/github/pr/opendp/opendp/678?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#743](https://github.com/opendp/opendp/pull/743) <a href="https://app.graphite.dev/github/pr/opendp/opendp/743?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#2384](https://github.com/opendp/opendp/pull/2384) <a href="https://app.graphite.dev/github/pr/opendp/opendp/2384?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2048** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2048?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#676** <a href="https://app.graphite.dev/github/pr/opendp/opendp/676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2450** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2450?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/opendp/opendp/2450?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2449** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2449?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2441** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2441?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2419** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2419?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: rust/src/combinators/sequential_composition/adaptive/mod.rs [hunk 1]
```diff
@@ -185,9 +182,9 @@ where
 
                 fallible!(FailedFunction, "unrecognized query: {:?}", query)
             })
-        })),
-        PrivacyMap::new_fallible(move |actual_d_in: &MI::Distance| {
-            if actual_d_in.total_gt(&d_in)? {
+        }),
+        PrivacyMap::new_fallible(move |d_in: &MI::Distance| {
+            if d_in.total_gt(&d_in_max)? {
```
Comment (mccalluc) [inline rust/src/combinators/sequential_composition/adaptive/mod.rs]: The previous state of this might have been more clear? The definition of `d_in_max` is a long ways away. There's probably more going on here than I realize.

File: rust/src/combinators/sequential_composition/non_adaptive/mod.rs [hunk 2]
```diff
@@ -70,26 +72,40 @@ where
...
+                    .map(|f| {
+                        // Wrap any spawned queryables with a check that no new queries have been asked.
+                        let child_id = *active_id.borrow();
+
+                        let wrapper = Wrapper::new_recursive_pre_hook(enclose!(active_id, move || {
+                            (*active_id.borrow() == child_id)
+                                .then_some(())
+                                .ok_or_else(|| err!(
+                                    FailedFunction,
+                                    "Compositor has received a new query. To satisfy the sequentiality constraint of composition, only the most recent release from the parent compositor may be interacted with."
```
Comment (mccalluc) [inline rust/src/combinators/sequential_composition/non_adaptive/mod.rs:100]: Is it feasible to give any information about _what_ query was received? Or the order? Thinking about what would be helpful for debugging.

Comment (Shoeboxam) [reply rust/src/combinators/sequential_composition/non_adaptive/mod.rs:100]: Unfortunately not, aside from the supporting elements (which are all equivalent), the measurements are essentially black boxes.

File: rust/src/combinators/sequential_composition/adaptive/mod.rs (hunk 1 above)
Comment (Shoeboxam) [reply rust/src/combinators/sequential_composition/adaptive/mod.rs]: Renamed to reduce potential ambiguity.
