### PR TITLE
fix: patch-free publish-able polars build

### LINKED ISSUE #2675: crates.io disallows wildcards in published dependencies
I had left the pyo3 dependency's version a wildcard, because it is totally determined by upstream crates, and only exists in our explicit dependency list so that I can enable Python 3.10 ABI 3. I wanted it to remain free so that our patch could then be more concise. 

However, an explicit version must be specified to publish on crates.io.

### PR DESCRIPTION
**Pull request by Shoeboxam**
I found build regressions in the non-patched polars version while testing the crates.io publish pipeline.

Ideally the crate publish path is checked as part of CI, but patches can only be disabled by simulating an entire publish (quite heavy) or doctoring the Cargo.toml. 

To be unmarked from draft once we see a successful release build push to crates.io:
https://github.com/opendp/opendp/actions/workflows/release.yml

### CODE REVIEW

File: rust/build/main.rs [hunk 1]
```diff
@@ -1,11 +1,23 @@
 #[cfg(feature = "derive")]
 mod derive;
 
+use std::process::Command;
```
Comment (mccalluc) [inline rust/build/main.rs:4]: Starting with the original issue:
> However, an explicit version must be specified to publish on crates.io

Is this something you're 100% sure about? If you have a link to docs that explained this for you, that could be useful to someone picking up this code later.

File: rust/build/main.rs [hunk 2]
```diff
@@ -1,11 +1,23 @@
...
+
 fn main() {
+    // causes patch_polars to update if patch is commented out
+    println!("cargo:rerun-if-changed=Cargo.toml");
+    println!("cargo:rerun-if-changed=Cargo.lock");
+
+    autocfg::emit_possibility("patch_polars");
```
Comment (mccalluc) [inline rust/build/main.rs:15]: Is this the "patch" you mention in the comment above? I'm a little confused about cause and effect, since this is below.

**Review by mccalluc — COMMENTED** [review]
Just skimming this.

Complexity worries me. If the root problem is that cargo requires dependencies to be pinned, I was just expecting to see the dependencies being pinned? Is this trying to preserve more flexibility? (Not so much interested in an explanation for me, but information for future maintainers, and maybe a consideration of alternatives.)

I think we want to list all the features in the documentation? https://docs.opendp.org/en/stable/contributing/development-environment.html#rust-feature-listing. If this is the right direction, the explanation there might help me understand this.

File: rust/build/main.rs (hunk 2 above)
Comment (Shoeboxam) [reply rust/build/main.rs:15]: Yes, this is the patch. It isn't a user-facing feature/something a user can configure.

File: rust/build/main.rs (hunk 1 above)
Comment (Shoeboxam) [reply rust/build/main.rs:4]: Yes, the CI was failing due to this.

**Comment by Shoeboxam** [comment]
This is ensuring that both the local build with the patch enabled, and the cargo publish build (with opendp as a dependency from crates.io, without the patch) builds. I didn't realize the publish version would not build.

**Comment by Shoeboxam** [comment]
Also, this is not actually a feature a user has control over, and as such shouldn't be documented on the features page. It's a build-time environment detection to adjust the crate to the correct Polars logic.

**Review by mccalluc — APPROVED** [review]
Thanks for explanation. I think I should take more time to understand this better, but that shouldn't block. Filed follow-up issue:
- #2705
