### PR TITLE
Inconsistent chain constructors

### LINKED ISSUE #36: Inconsistent chain constructors
In the changes for #30, we messed up something, and now test.py is crashing:

```
/usr/local/bin/python3.8 /Users/av/Projects/opendp/python/test.py
Initialized OpenDP Library
"hello, world!"

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

The crash happens at line 38:

```
    everything = odp.core.make_chain_tt(composition, parse_dataframe)
```

### PR DESCRIPTION
**Pull request by andrewvyrros**
Fixes #36.

### CODE REVIEW

File: rust/opendp/src/core.rs [hunk 1]
```diff
@@ -461,6 +461,38 @@ impl<D: 'static + Domain, M: 'static + Metric> MetricGlue<D, M> {
 // CHAINING & COMPOSITION
 pub struct ChainMT;
 
+impl ChainMT {
+    pub fn make_chain_mt_glue<DI, DX, DO, MI, MX, MO>(
```
Comment (Shoeboxam) [inline rust/opendp/src/core.rs:465]: Perhaps we call these `make_with_glue`? Then they are called like `ChainMT::chain_with_glue(...)` instead of ChainMT::make_chain_mt_glue(...)`.

**Review by Shoeboxam — APPROVED** [review]
