### PR TITLE
fix: always default to include inf in float domains

### LINKED ISSUE #2465: always default to include inf in domains

### PR DESCRIPTION
**Pull request by Shoeboxam**
Close #2465

### CODE REVIEW

**Comment by Shoeboxam** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/opendp/opendp/2466?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2466** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/opendp/opendp/2466?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2220** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2220?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#938](https://github.com/opendp/opendp/pull/938) <a href="https://app.graphite.dev/github/pr/opendp/opendp/938?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#2106](https://github.com/opendp/opendp/pull/2106) <a href="https://app.graphite.dev/github/pr/opendp/opendp/2106?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2384** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2384?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#745](https://github.com/opendp/opendp/pull/745) <a href="https://app.graphite.dev/github/pr/opendp/opendp/745?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#678** <a href="https://app.graphite.dev/github/pr/opendp/opendp/678?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#743](https://github.com/opendp/opendp/pull/743) <a href="https://app.graphite.dev/github/pr/opendp/opendp/743?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2048** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2048?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2457** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2457?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#676** <a href="https://app.graphite.dev/github/pr/opendp/opendp/676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2450** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2450?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2449** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2449?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2441** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2441?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2419** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2419?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: rust/src/measurements/canonical_noise/mod.rs [hunk 1]
```diff
@@ -63,7 +66,8 @@ pub fn make_canonical_noise(
         Approximate(MaxDivergence),
         Function::new_fallible(move |&arg: &f64| {
             let canonical_rv = CanonicalRV {
-                shift: RBig::try_from(arg).unwrap_or(RBig::ZERO),
+                shift: RBig::try_from(arg.clamp(f64::MIN_FINITE, f64::MAX_FINITE))
```
Comment (mccalluc) [inline rust/src/measurements/canonical_noise/mod.rs]: I'm surprised it's not plain `MIN` and `MAX`?
https://doc.rust-lang.org/std/primitive.f64.html#associatedconstant.MAX

**Review by mccalluc — APPROVED** [review]

File: rust/src/measurements/canonical_noise/mod.rs (hunk 1 above)
Comment (Shoeboxam) [reply rust/src/measurements/canonical_noise/mod.rs]: Since there's no generics here, min and max will actually work. They are both the same, I'd just been using the `*_FINITE` variants because in other settings I needed it as a trait.

Comment (Shoeboxam) [reply rust/src/measurements/canonical_noise/mod.rs]: Switched.
