### PR TITLE
Fixed tuple issues in opendp_data__object_as_slice()

### LINKED ISSUE #97: opendp_data__object_as_slice() doesn't handle (AnyObject, AnyObject)
In the refactoring of #88, we lost the ability to handle tuples of AnyObject. This is probably OK in the inbound direction (`opendp_data__slice_as_object()`), because it's unlikely for an operation to consume a tuple like that. But that kind of tuple is produced by basic composition, so we should support it in the outbound direction (`opendp_data__object_as_slice()`).

### PR DESCRIPTION
**Pull request by andrewvyrros**
Closes #97.

Note that, snuck into this change, there's a cfg thing in dispatch.rs so that dev and test builds will compile with a limited set of types for faster monomorphization. If this is a problem, I'm happy to back it out and keep it in my own clone.

* Cleaned up tuple logic.
* Added AnyObject support to type dispatch.
* Wrote some unit tests to cover tuple cases.
* Made a cfg with a stripped-down set of types for fast compilation of dev target.
* Picked up suggested tweaks from #96 PR review.

### CODE REVIEW

File: rust/opendp-ffi/src/data/mod.rs [hunk 1]
```diff
@@ -67,13 +66,10 @@ pub extern "C" fn opendp_data__slice_as_object(raw: *const FfiSlice, T: *const c
...
-                // primitively typed tuples
-                dispatch!(raw_to_tuple, [(types[0], @primitives), (types[1], @primitives)], (raw))
-            } else {
-                // boxy tuples
-                dispatch!(raw_to_plain, [(T, @primitives)], (raw))
-            }
+            let types = try_!(element_ids.iter().map(Type::of_id).collect::<Fallible<Vec<_>>>());
+            // In the inbound direction, we can handle tuples of primitives only. This is probably OK,
+            // because the only likely way to get a tuple of AnyObjects is as the output of composition.
+            dispatch!(raw_to_tuple, [(types[0], @primitives), (types[1], @primitives)], (raw))
```
Comment (Shoeboxam) [inline rust/opendp-ffi/src/data/mod.rs:72]: It's nice to get this cleaned up.

File: rust/opendp-ffi/src/dispatch.rs [hunk 2]
```diff
@@ -97,6 +105,41 @@ macro_rules! disp_expand {
     };
 }
 
+#[cfg(debug_assertions)]
```
Comment (Shoeboxam) [inline rust/opendp-ffi/src/dispatch.rs:108]: Looking forward to the quicker debug loop!

**Review by Shoeboxam — APPROVED** [review]
