### PR TITLE
fix: additive noise sampler bias, statistical testing

### LINKED ISSUE #2638: Bias in additive noise samplers
Thank you for raising the issue Cesare Caratozzolo!

The implementation of RBig / UBig division in the bignum math library Dashu is bugged:
https://github.com/cmpute/dashu/issues/57

This manifests in a bias in the additive noise mechanisms.

### PR DESCRIPTION
**Pull request by Shoeboxam**
Closes #2638 

* replaced buggy implementation of rational division in Dashu
* expanded the statistical testing suite

The new test suite:
* Bernoulli(p=x) across f32, f64 and rational
    * wilson tests at fixed points and powers of 2
    * test that constant-time float sampling does not affect distributional output
    * extreme points
* Bernoulli(p=e^-x) - the exp1 and exp samples from CKS20
    * wilson tests at fixed points
    * test that the probability factorizes
    * test that probabilities decrease monotonically as x increases
    * extreme points (0, 1, large rationals)
* gcd - deterministic tests
* Geometric(p=1 - exp(-x)) - the fast and slow geometric samplers from CKS20
    * chisq test for binned discrete outcomes
    * test moments at fixed points
    * test that fast and slow sampler moments match
    * extreme points
* DiscreteLaplace(scale=s)
    * test zero mass and mean
    * test symmetry
    * test binned chisq goodness of fit
    * test tail bounds for fixed points
    * test log ratio
    * extreme points
* DiscreteGaussian(scale=s)
    * test zero mass and second moment
    * test symmetry
    * test binned chisq goodness of fit
    * test tail bounds for fixed points
    * test quadratic log ratio
    * extreme points
* Uniform(0, k) across native types and UBig
    * chisq goodness of fit across fixed points

I also adjusted the implementation of the kolmogorov-smirnov test and sample sizes to increase power.

### CODE REVIEW

File: rust/src/measurements/noisy_top_k/test.rs [hunk 1]
```diff
@@ -8,18 +8,21 @@ use super::*;
 #[test]
 fn test_rnm_gumbel_distribution_varied() -> Fallible<()> {
     let scores: [_; 10] = from_fn(|i| i);
-    let trials = 1000;
-    let mut observed = [0.0; 10];
+    let trials = 10_000;
```
Comment (mccalluc) [inline rust/src/measurements/noisy_top_k/test.rs:12]: Others just bumped up to 5000: This one needs to be stronger?

File: rust/src/measurements/noisy_top_k/test.rs [hunk 2]
```diff
@@ -150,48 +153,47 @@ fn test_permute_and_flip() {
...
     (0..1000).try_for_each(|_| {
-        observed[permute_and_flip(&scores, &rbig!(0), false)?] += 1.0;
+        if permute_and_flip(&scores, &rbig!(0), false)? != 9 {
+            panic!("P&F with zero scale should deterministically select last index");
+        }
         Fallible::Ok(())
-    })?;
-    let mut expected = [0.0; 10];
-    expected[0] = 1000.0;
-    check_chi_square(observed, expected)
```
Comment (mccalluc) [inline rust/src/measurements/noisy_top_k/test.rs:160]: Dropping `check_chi_square` is intentional?

File: rust/src/traits/samplers/bernoulli/test.rs [hunk 3]
```diff
@@ -1,43 +1,116 @@
...
+        rbig!(0 / 1),
+        rbig!(1 / 16),
+        rbig!(1 / 8),
+        rbig!(1 / 4),
+        rbig!(3 / 8),
+        rbig!(1 / 2),
+        rbig!(3 / 4),
+        rbig!(15 / 16),
+        rbig!(1 / 1),
+    ];
```
Comment (mccalluc) [inline rust/src/traits/samplers/bernoulli/test.rs:32]: I'm a little surprised by the coverage here: It's a pretty long list, but it's also leaving out cases. If any of these could be a problem, would you like to just loop from 0 to 16 and try them all? Or maybe simplify in the other direction: I don't have a good intuition.

File: rust/src/traits/samplers/bernoulli/test.rs [hunk 4]
```diff
@@ -1,43 +1,116 @@
...
+    for &p in &ps {
+        run_wilson_test_float::<f32>(p, false, N_FLOAT / 2, "bernoulli_float f32 non-ct");
+        run_wilson_test_float::<f32>(p, true, N_FLOAT / 2, "bernoulli_float f32 ct");
+    }
+}
+
+#[test]
+fn bernoulli_float_constant_time_and_nonconstant_match_f64() {
+    // Compare ct vs non-ct at same p via a mean-difference test
+    let ps: [f64; 6] = [0.01, 0.1, 0.3, 0.5, 0.9, 0.99];
```
Comment (mccalluc) [inline rust/src/traits/samplers/bernoulli/test.rs]: `ps` are similar, but not identical in all of these: If they could all be the same, just define the set once... but if the differences do matter, explain why?

File: rust/src/traits/samplers/bernoulli/test.rs [hunk 5]
```diff
@@ -1,43 +1,116 @@
...
+        assert!(sample_bernoulli_float::<f64>(1.0, true)?);
+    }
+    Ok(())
+}
+
+#[test]
+fn wilson_float_f64_fixed_points() {
+    let ps: Vec<f64> = vec![0.0, 0.5, 0.25, 0.125, 0.75, 0.1, 0.2, 0.3, 0.7, 0.99];
+    for &p in &ps {
+        run_wilson_test_float::<f64>(p, false, N_FLOAT, "bernoulli_float f64 non-ct");
```
Comment (mccalluc) [inline rust/src/traits/samplers/bernoulli/test.rs]: Re: `bernoulli_float f64 non-ct`, and similar below. These messages seem short to me: Would it help a future maintainer to fill them out a little more?

File: rust/src/traits/samplers/cks20/test/bernoulli.rs [hunk 6]
```diff
@@ -0,0 +1,301 @@
...
+
+    let sampler = |x: RBig| sample_bernoulli_exp1(x).unwrap();
+    test_fixed_points_wilson(sampler, &xs, N_BERNOULLI, ALPHA, "exp1 fixed point");
+}
+
+#[test]
+fn exp1_is_monotone_decreasing() {
+    let xs = vec![
+        rbig!(0 / 1),
+        rbig!(1 / 8),
```
Comment (mccalluc) [inline rust/src/traits/samplers/cks20/test/bernoulli.rs]: Similar question about coverage: if `1/16` is interesting above, is it also interesting here? Just create `xs` once?

File: rust/src/traits/samplers/cks20/test/bernoulli.rs [hunk 7]
```diff
@@ -0,0 +1,301 @@
...
+
+fn big_denom_rationals_in_0_1() -> Vec<RBig> {
+    vec![
+        RBig::from(1i64) / RBig::from(1i64 << 30),
+        RBig::from(3i64) / RBig::from(1i64 << 30),
+        RBig::from(1i64) / RBig::from(65_537i64),
+        RBig::from(32_768i64) / RBig::from(65_537i64),
+        RBig::from(65_536i64) / RBig::from(65_537i64),
+        RBig::from(12_345i64) / RBig::from(1_000_003i64),
+        RBig::from(999_983i64) / RBig::from(1_000_003i64),
```
Comment (mccalluc) [inline rust/src/traits/samplers/cks20/test/bernoulli.rs:254]: I recognize the powers of 2, but if these numbers are also special, add an explanation?

File: rust/src/traits/samplers/cks20/test/bernoulli.rs [hunk 8]
```diff
@@ -0,0 +1,301 @@
...
+#[test]
+fn exp_factorization_holds_for_large_denominators() {
+    let n = N_BERNOULLI;
+    let xs = big_denom_rationals_in_0_1();
+
+    let pairs: Vec<(RBig, RBig)> = vec![
+        (xs[0].clone(), xs[2].clone()),
+        (xs[1].clone(), xs[5].clone()),
+        (xs[3].clone(), xs[2].clone()),
+        (xs[4].clone(), xs[0].clone()),
```
Comment (mccalluc) [inline rust/src/traits/samplers/cks20/test/bernoulli.rs]: If there's a significance to particular pairs here, it's not obvious.

File: rust/src/traits/samplers/cks20/test/bernoulli.rs [hunk 9]
```diff
@@ -0,0 +1,301 @@
...
+        assert_factorizes_addition_empirical(&a, &b, n);
+    }
+}
+
+#[test]
+fn exp_scaling_identity_holds_for_large_denominators() {
+    let n = N_BERNOULLI;
+
+    let x1 = RBig::from(1i64) / RBig::from(65_537i64);
+    let x2 = RBig::from(12_345i64) / RBig::from(1_000_003i64);
```
Comment (mccalluc) [inline rust/src/traits/samplers/cks20/test/bernoulli.rs:274]: More meaningful names? `one_over_big_power_of_two`, `big_relative_primes`

File: rust/src/traits/samplers/cks20/mod.rs [hunk 10]
```diff
@@ -61,9 +87,17 @@ use super::{sample_bernoulli_rational, sample_standard_bernoulli, sample_uniform
...
 fn sample_bernoulli_exp1(x: RBig) -> Fallible<bool> {
+    let (numer_signed, denom) = x.into_parts();
+    let (Sign::Positive, numer) = numer_signed.into_parts() else {
+        return fallible!(FailedFunction, "x must be in [0, 1]");
+    };
+
     let mut k = UBig::ONE;
     loop {
-        if sample_bernoulli_rational(x.clone() / &k)? {
+        // Build x/k with corrected exact division, bypassing buggy RBig `/`.
```
Comment (mccalluc) [inline rust/src/traits/samplers/cks20/mod.rs:97]:
```suggestion
        // Build x/k with corrected exact division, bypassing buggy RBig `/`.
        // Drop when fix is available upstream: https://github.com/cmpute/dashu/issues/57
```

File: rust/src/measurements/noisy_top_k/test.rs (hunk 2 above)
Comment (Shoeboxam) [reply rust/src/measurements/noisy_top_k/test.rs:160]: It's still there.
